### ISSUE TITLE
Upload deck to github

### ISSUE THREAD

**Issue by AkimParis** [langfield/ki#124]
Hey guys,

I want to upload one particular deck (not my full collection) to my GitHub in order to work in a collaborative way.
Should I use git commands or do you have particular ki commands? 

Thx!

**Comment by langfield** [comment]
@AkimParis Yes, there is a script for this. Try looking at [this](https://github.com/langfield/ki/blob/main/submodule.py). It hasn't been used in a while, so I may need to spruce it up for you a bit. Let me know how you fair, and I'll fix any problems you run into! 😁

**Comment by AkimParis** [comment]
I am sorry but I am confused about the syntax...

git-submodule push DeckName https://github.com/name/XYZ.git 
or 
git push DeckName https://github.com/name/XYZ.git 

Thx!

**Comment by langfield** [comment]
Try this:
```console
python3 ./<path_to_script>/submodule.py --kirepo <path_to_ki_repository> --deck <deck_name> --remote git@github.com:name/xyz.git
```
Make sure you give it the correct location of the `submodule.py` script, which I linked above. Also make sure to use the proper path separators for your operating system.

**Comment by langfield** [comment]
@AkimParis Any luck?

**Comment by AkimParis** [comment]
I couldn't find the submodule.py... Did you change something?!

**Comment by langfield** [comment]
Hi, there is a link to the script above. [Here it is.](https://github.com/langfield/ki/blob/main/submodule.py).

**Comment by AkimParis** [comment]
Sorry dude but I don't have a submodule.py in my local KI folder...

**Comment by langfield** [comment]
Hi @AkimParis, sorry for the misunderstanding. You are not supposed to have such a script anywhere inside the repository. The script is available at the link I provided. You must either clone this project to get the script, or download it directly at that link. It is not installed anywhere on your `$PATH` by default.

**Comment by AkimParis** [comment]
Alright, I clone the submodule and pip install git-filter-repo... 
It seems to work. I got a small problem identifying the path of the kirepo and the deck.

It's the paths: 
ki -> C:\Users\Name\anaconda3\Lib\site-packages\ki ... 
decks -> C:\Users\Name\collection  

Error: ki.types.NotKiRepoError: fatal: not a ki repository (or any parent up to mount point /)
Stopping at filesystem boundary.

Almost there... : )

**Comment by langfield** [comment]
Hi! In the example I gave you, the `--kirepo` argument in the path to your collection repository, called a `kirepo`/ki repository because it is created by `ki`, but I understand the confusion. The `--deck` argument is the path to the specific deck you want to host on Github.

If you cloned your collection into your home directory at `collection/`, and the deck you want to upload is `collection/Default/a/`, then you would run:
```console
python3 ./<path_to_script>/submodule.py --kirepo collection --deck Default/a/ --remote git@github.com:name/xyz.git
```

Try running `python3 submodule.py --help` if you're having trouble!

**Comment by AkimParis** [comment]
Sorry, I don't use Git a lot at work, so I am confused. Ok, I understand better now. 

My full CLI to share my deck on my GitHub: 
python C:\Users\Kikim\anaconda3\Lib\site-packages\ki\submodule.py --kirepo collection --deck c:/users/kikim/collection/Vocabulary-JAP-AI-NLP-CV-AkimfromParis --remote git@github.com/AkimParis/anki_jap_ai_vocabulary.git 


And I got the following answer:
Operating on 'C:\Users\Kikim\AppData\Local\Temp\tmpgp0kr6bc\submodule-143551385322c4974405cf0de1bc7135b285f7a8'
Error: --path-rename expects one colon in its argument: <old_name:new_name>. 

I believe something is going on with git-filter-repo....

**Comment by langfield** [comment]
Try passing a relative path to the deck:
```console
python C:\Users\Kikim\anaconda3\Lib\site-packages\ki\submodule.py --kirepo collection --deck Vocabulary-JAP-AI-NLP-CV-AkimfromParis --remote [git@github.com](mailto:git@github.com)/AkimParis/anki_jap_ai_vocabulary.git
```

**Comment by AkimParis** [comment]
Ok, I switched from SSH to HTTPS. And it worked... 

It's more than 400 flashcards in Japanese for vocabulary about machine learning (from statistics to deep learning models). Now, I will ask Japanese developers for help on Qiita. Hopefully, they will help with this deck. ; )

**Comment by langfield** [comment]
Glad it's working for you! 😄
