### ISSUE TITLE
Broken link to syntax-higlighting add-on

### ISSUE THREAD

**Issue by Mxbonn** [langfield/ki#126]
The link in The documenation about: "Example: generating syntax-highlighted code blocks" is broken
https://github.com/langfield/ki/blob/fed9977fac349eedc0268427d0be7b979fd49651/ki/DOCUMENTATION.md?plain=1#L654

**Comment by Mxbonn** [comment]
And unrelated, but since I dont want to flood you with pull requests: the installation guide does not mention anywhere that you need to have `html-tidy` installed.

**Comment by langfield** [comment]
Hey, no please do flood with PRs or issues! Apologies, this is a particularly busy time at work.

You're definitely right, this should be fixed. As you can tell, the documentation is sorely out-of-date.

Feel free to point out any more typos or issues. Also let me know how you're getting on with using the tool itself!

**Comment by langfield** [comment]
Yes, that is possible! There is a standalone script in the repository for automating some of this process. It is called "submodule.py".
________________________________
