### ISSUE TITLE
Use pipx instead of pip to install

### ISSUE THREAD

**Issue by VaiTon** [langfield/ki#135]
- pipx [^1] create an isolated venv for the package
- doesn't need admin permissions
- the installation command is the same
```bash
pipx install git+https://github.com/langfield/ki.git
```

[^1]: https://pypa.github.io/pipx/

**Comment by langfield** [comment]
Thanks for the interest! Sorry, I probably won't do this. The state of `venv`-like solutions in python [is crazy](https://stackoverflow.com/questions/41573587/what-is-the-difference-between-venv-pyvenv-pyenv-virtualenv-virtualenvwrappe) and I want no part of it. Also, `pip` doesn't need admin permissions unless you're messing with your system python (which you probably shouldn't be).

**Comment by VaiTon** [comment]
Fair enough, but keep in mind that:
- `pipx` is maintained by the [PyPA](https://github.com/pypa)
- A lot of problems regarding dependency conflicts etc can be completely avoided with pipx, as it creates (without any user interaction) a virtualenv and installs the required packages.

At least maybe adding a reference to the fact that it can be used could be good for newcomers, but your project your rules
