### ISSUE TITLE
Trying to understand if ki is good for my goals (not a programmer)

### ISSUE THREAD

**Issue by DallMit** [langfield/ki#140]
I will try to describe my use case in detail
What I want: Kanji from my Anki deck must automatically get highlighted on any website I visit (Google chrome)
My solution: Install https://chrome.google.com/webstore/detail/word-highlighter/flpifgahbaopfmnlmcgkkodanhoifdpa , export my anki deck cards in plain text, edit them so that they fit the extension structure, import them into the extension.
Had a problem: Extension sometimes highlighted only half of a compound kanji, for example 神曲
I have 神 in my list, but not the full 神曲. Solved it by making a second group in the extension with unlearned kanji, so that they are marked in a different color. Have to add them manually one by one as I meet them.

So, I am now searching for something that will automatically pull cards from my anki decks and convert them to a list with a format 1 kanji-1 row.

It would be ideal for that list to get automatically uploaded into the extension, but that seems too hard without working with the dev of that extension and it seems abandoned.

So for now, I want:
List 1 - Automatically generated from my anki deck 1. Has only one kanji on every row. My main deck
List 2 - Automatically generated from my anki deck 2. Has only one kanji on every row. Deck with compound kanji I did not learn yet.
I manually paste these lists into groups in the extension to update my highlights.
Can ki automatically generate these lists?

**Comment by langfield** [comment]
Even if you use this tool, it's going to give you cards in a very specific markdown format. You'll have to do some programming either way in order to construct the lists you want. There is likely no quicker way than learning enough python to generate these lists by interfacing with the Anki API (or paying someone to do it for you).

**Comment by DallMit** [comment]
Alright, I will try to do it with guidance from chatgpt, since it possible to do with ki
