### ISSUE TITLE
BeartypeCallHintParamViolation when installing via virtualenv or pipx

### ISSUE THREAD

**Issue by natefduncan** [langfield/ki#171]
First off, thank you for your work on this project. This is exactly the kind of thing I was looking for. 

When I tried to install this via virtualenv and pipx on Arch, I get a `BeartypeCallHintParamViolation` when I run `ki clone`. I think this is because the install doesn't include the `.github` folder and `empty_kirepo` in `ki/maybes.py` doesn't like that those files don't exist (line 474).

**Comment by natefduncan** [comment]
It works if I `pip3 install --editable .` after cloning the repo. 

Is there a reason `.github` files are copied into collections?

**Comment by langfield** [comment]
Hi! 😀 Working on a fix for this. Yes, we copy a workflow file to each newly created repository so that if/when you create a subdeck repo, we can drop this workflow into it and pushes to GitHub will automatically generate a pages website with all notes rendered. See #41 and #168.

**Comment by langfield** [comment]
Try uninstalling and then reinstalling like this:
```console
python3 -m pip install git+https://github.com/langfield/ki.git@fix-package-manifest
```
and let me know how it goes!

**Comment by natefduncan** [comment]
Yup, that's working for me now. Thank you!
