### ISSUE TITLE
How am I supposed to create new cards?

### ISSUE THREAD

**Issue by m0tholith** [langfield/ki#175]
I made my decks in Anki and one single note to go off of. How do I add a new one? Do I keep notes in separate files or group them by deck? What values do I put in the `guid` field?

**Comment by m0tholith** [comment]
I made a script that generates a random string with a specified length, it's just this one-liner `tr -dc 'A-Za-z0-9' </dev/urandom | head -c 30; echo` but when I enter vim I make a macro to run the command on the current line and prepend the contents with guid: " (`:silent .!random-str`). I also made a snippet (in the luasnip engine) to automatically insert a basic note:
```lua
-- ~/.config/lua/ftplugin/markdown.lua

local luasnip = require("luasnip")
local snippet = luasnip.snippet
local t = luasnip.text_node
local i = luasnip.insert_node

luasnip.add_snippets("markdown", {
    snippet("ankinote", {
        t({ "# Note", "```" }),
        t({ "", "guid: " }),
        i(1),
        t({ "", "notetype: " }),
        i(2, "Basic (and reversed card)"),
        t({ "", "```" }),

        t({ "", "", "### Tags", "```" }),
        i(3),
        t({ "", "```" }),

        t({ "", "", "## Front", "" }),
        i(4),

        t({ "", "", "## Back", "" }),
        i(0),
    }),
})
```
I think that it would be easier, when running `ki push`, if ki automatically populates GUIDs which have empty fields.

**Comment by langfield** [comment]
Hi! It's a nice solution! I chose not to implement this functionality because if the file is changed during a push, the working tree would be modified, and so the commit that was made is not what is actually being pushed. Alternatively, the push command could make an additional commit. I think both of these violate the expected behavior of a git-push-like command in an unacceptable way. 🤷‍♀️

Furthermore it makes it difficult to distinguish between a note with a missing GUID because something went wrong during an "import" and a note with an intentionally blank GUID.
________________________________

**Comment by langfield** [comment]
Thanks very much for trying out the tool, by the way! I really appreciate detailed feedback like this, and I'd love to know if anything else isn't quite working for you, and how you're using it.
________________________________

**Comment by m0tholith** [comment]
> Hi! It's a nice solution! I chose not to implement this functionality because if the file is changed during a push, the working tree would be modified, and so the commit that was made is not what is actually being pushed. Alternatively, the push command could make an additional commit. I think both of these violate the expected behavior of a git-push-like command in an unacceptable way. 🤷‍♀️ Furthermore it makes it difficult to distinguish between a note with a missing GUID because something went wrong during an "import" and a note with an intentionally blank GUID.

Ah, I see. I guess it's not that bad since it's so fast to create notes anyway!

> Thanks very much for trying out the tool, by the way! I really appreciate detailed feedback like this, and I'd love to know if anything else isn't quite working for you, and how you're using it.

ki is an awesome tool, thank you for putting the time and effort into making this! It's actually been really stable for me, at least when I use it right :sweat_smile:
I specifically use it for making german flashcards since it's just a little setup and I'm all set to revise all the words I've learned so far. It's awesome!

**Comment by langfield** [comment]
Lovely! I am very glad to hear it's working for you :)
