### ISSUE TITLE
Invalid img src when writing back to Anki

### ISSUE THREAD

**Issue by KarelZe** [langfield/ki#64]
@langfield Thanks for your work. During my tests for https://github.com/KarelZe/anki-decks/issues/4 I ran into an issue, that is probably related with pushing back to anki for binary generation.

For some images the link in Anki is incorrect, so the image can't be loaded. This is however only true for some images. Here is an example from my recommender deck:

**Markdown file as in [your repo](https://github.com/langfield/karelze-anki-decks/blob/master/%F0%9F%A7%99%E2%80%8DRecommendersysteme/wie-sieht-die-linkstruktur-von-einem-hub.md):** ✅
```
## Note
nid: 1616243314081
model: Basic-b122e
tags: 12_relevante_objekte_empfehlen
markdown: false

### Front
Wie sieht die Linkstruktur von einem Hub in einem Web-Graphen aus?

### Back
Ein guter Hub zeigt auf viele Authorities:
<div><img src=
"paste-64c7a314b90f3e9ef1b2d94edb396e07a121afdf.jpg"></div>
```

**HTML in Anki after import:** ❌
```
Ein guter Hub zeigt auf viele Authorities:
<div><img src="%0A" paste-64c7a314b90f3e9ef1b2d94edb396e07a121afdf.jpg""=""></div>
```

This results in multiple image files not being found:

![image](https://user-images.githubusercontent.com/12801659/185786618-0688bdd9-7d69-4551-90f9-ca106d39bf15.png)

**Comment by langfield** [comment]
@KarelZe A **first-class** error report if I do say so myself! :trophy: I have indeed reproduced the issue on my own machine, and I believe it has to do with how `"` (double-quote) characters are being encoded/decoded. I am writing a test for this as we speak! It shall be fixed! :detective:

**Comment by langfield** [comment]
For posterity, note that in `qt/aqt/editor.py` within the Anki codebase, we have:
```python
    def loadNote(self, focusTo: int | None = None) -> None:
        if not self.note:
            return

        data = [
            (fld, self.mw.col.media.escape_media_filenames(val))
            for fld, val in self.note.items()
        ]
```
and it's this call to `MediaManager.escape_media_filenames()` that is messing with the double quotes.

The preliminary solution appears to be just stripping the double quotes out from the tag. Then the above function just puts them back in for us.
